name: CI/CD Pipeline

on:
  push:
    branches:
      - Prod
      - Stage
      - Dev

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    # Dynamically set the environment based on the branch name
    environment: ${{ github.ref_name == 'Prod' && 'Production' || github.ref_name == 'Stage' && 'Staging' || github.ref_name == 'Dev' && 'Development' }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Install Luau
        uses: EncodedVenom/install-luau@v4.3
        with:
          verbose: false
          version: latest
          
      - name: Rojo Build
        uses: CompeyDev/rojo-build-action@0.1.5
        with:
            # File to write to (excluding file type)
            output: ../ROBLOX_PLACE_FILE
            # The type of file to be outputted
            type: rbxl
            # Directory to run the build in
            working-directory: .
            
      - name: Verify Output File
        run: ls ..
        
      - name: Upload to Roblox
        uses: Ulferno/upload-to-roblox@v1.0.4
        with:
          # Pulling secrets from the environment
          api-key: ${{ secrets.API_KEY }}
          universeId: ${{ secrets.UNIVERSE_ID }}
          placeId: ${{ secrets.PLACE_ID }}
          file: ../ROBLOX_PLACE_FILE.rbxl
          # Optionally set shouldPublish from a secret or default to true
          shouldPublish: ${{ secrets.SHOULD_PUBLISH || 'true' }}

